# Generated by Django 5.1 on 2024-08-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_remove_student_roll_student_email_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='def.png', null=True, upload_to='images/'),
        ),
    ]
