# Generated by Django 5.1 on 2024-08-31 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='image',
            new_name='img',
        ),
    ]
